name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # আপনার ব্রাঞ্চ নাম main বা master যা হবে তা দিন

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inject Secret Token
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          sed -i "s/__BOT_TOKEN__/$BOT_TOKEN/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
